#!/usr/bin/env python
# Python 2.6.2
# Name: tabulator.py
# Author: Mike Anderson
# Created: Aug 5, 2009
# Purpose: To define a class that takes as input a merged BallotInfo
#  file and generates a report

import yaml
import sys
from datetime import date

import audit_header

class Tabulator(object):
    def __init__(self, args):
        # Load ballot records from yaml file
        self.input = args[0]
        self.precs = 0
        try:
            print args
            stream = open(self.input + '.yaml', 'r')
        except:
            print('Unable to open ' + self.input + '\n')
            exit(0)
        else:
            a = audit_header.AuditHeader()
            a.load_from_file(stream)
            self.b = list(yaml.load_all(stream))

        # If a jurisdiction_slate filename was given, then load its
        #  contents
        if len(args) == 2:
            try:
                stream = open(args[1] + '.yaml', 'r')
            except:
                print('Unable to open ' + self.input + '\n')
                exit(0)
            else:
                a = audit_header.AuditHeader()
                a.load_from_file(stream)
                self.j = yaml.load_all(stream)
        else:
            self.j = False

        # Add the vote counts of candidates with the same ID# using
        #  sumation(). Write the vote totals for each candidate to the
        #  report stream.
        self.serialize_csv(self.sumation())

    # Sum up the separate vote counts in each record for each candidate
    #  and return the cumulative result as a dictionary.
    def sumation(self):
        cont_list = []
        sum_list = []
        prec_list = set()
        for i in range(len(self.b)):
            if self.j:
                prec_list = prec_list.union([self.b[i]['ident']])
            for ii in range(len(self.b[i]['contests'])):
                if i == 0:
                    sum_list.append({})
                    cont_name = self.b[i]['contests'][ii]['display_name']
                    sum_list[ii]['cont_name'] = cont_name
                    sum_list[ii]['cands'] = {}
                for iii in range(len(self.b[i]['contests'][ii]['candidates'])):
                    n =self.b[i]['contests'][ii]['candidates'][iii]['display_name']
                    if not sum_list[ii]['cands'].has_key(n):
                        sum_list[ii]['cands'][n] = 0
                    c_count = self.b[i]['contests'][ii]['candidates'][iii]['count']
                    sum_list[ii]['cands'][n] += c_count
        self.precs = len(prec_list)
        print sum_list
        return sum_list

    # Serialize a list of contests and their respective candidate vote
    #  counts into a .csv format, and output them to a file
    def serialize_csv(self, sum_list):
        stream = open(self.input + '_report.csv', 'w')
        stream.write('Election Summary Report,,\n')
        stream.write(
           'Generated by TrustTheVote Tabulation and Reporting Module,,\n')
        d = date.today()
        stream.write('Report generated on, ' +
                     str(d.month) + '-' + str(d.day) + '-' + str(d.year) + '\n')
        if self.input.rfind('/') != -1:
            fname = self.input[self.input.rfind('/') + 1:]
        else:
            fname = self.input
        stream.write('Input BallotInfo File, ' + fname + '.yaml\n')
        stream.write(',,\n')
        for cont in sum_list:
            stream.write(',,\n')
            stream.write('Contest,Label,Total\n')
            stream.write(cont['cont_name'] + \
                         ',Number of Precincts,' + str(self.precs) + '\n')
            for name in cont['cands'].keys():
                stream.write(','+ name +','+ str(cont['cands'][name]) +'\n')
        stream.close()

def main():
    # Output a usage message if incorrect number of command line args
    if( len(sys.argv) != 2 and len(sys.argv) != 3 ):
        print "Usage: [MERGED INPUT FILE]"
        print "    OR [MERGED INPUT FILE] [JURISDICTION FILE]"
        exit()

    t = Tabulator(sys.argv[1:])

    print 'SOVC report created in ' + sys.argv[1] + '_report.csv\n'

    return 0

if __name__ == '__main__': main()
